version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: rms
      MYSQL_PASSWORD: 123456
    ports:
      - 3307:3306
    networks:
      - backendNetwork
  app:
    image: app:latest
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - frontendNetwork
      - backendNetwork
  angular:
    image: angular:latest
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - app
    networks:
      - frontendNetwork
networks:
  frontendNetwork:
  backendNetwork: